; jajaran genjang (persegi panjang)
(deffacts tc10
    (tes 10)
    (ans "jajaran genjang (persegi panjang)")
    (objek (sisi 4))
    (sisi (from 1) (to 2) (length 40.0))
    (sisi (from 2) (to 3) (length 20.0))
    (sisi (from 3) (to 4) (length 40.0))
    (sisi (from 4) (to 1) (length 20.0))
    (paralel (jumlah 2))
    (sudut (id 1) (degree 90.0))
    (sudut (id 2) (degree 90.0))
    (sudut (id 3) (degree 90.0))
    (sudut (id 4) (degree 90.0))
)