; jajaran genjang beraturan
(deffacts tes11
    (tes 11)
    (ans "jajaran genjang beraturan")
    (objek (sisi 4))
    (sisi (from 1) (to 2) (length 20.0))
    (sisi (from 2) (to 3) (length 20.0))
    (sisi (from 3) (to 4) (length 20.0))
    (sisi (from 4) (to 1) (length 20.0))
    (jumlah-paralel (jumlah 2))
    (sudut (id 1) (degree 90.0))
    (sudut (id 2) (degree 90.0))
    (sudut (id 3) (degree 90.0))
    (sudut (id 4) (degree 90.0))
)