; segiempat tidak beraturan
(deffacts tc8
    (tes 8)
    (ans "segiempat tidak beraturan")
    (objek (sisi 4))
    (sisi (from 1) (to 2) (length 20.0))
    (sisi (from 2) (to 3) (length 40.0))
    (sisi (from 3) (to 4) (length 40.0))
    (sisi (from 4) (to 1) (length 20.0))
    (paralel (jumlah 0))
    (sudut (id 1) (degree 90.0))
    (sudut (id 2) (degree 120.0))
    (sudut (id 3) (degree 30.0))
    (sudut (id 4) (degree 120.0))
)