; jajaran genjang (jajar genjang)
(deffacts tc9
    (tes 9)
    (ans "jajaran genjang (jajar genjang)")
    (objek (sisi 4))
    (sisi (from 1) (to 2) (length 40.0))
    (sisi (from 2) (to 3) (length 20.0))
    (sisi (from 3) (to 4) (length 40.0))
    (sisi (from 4) (to 1) (length 20.0))
    (jumlah-paralel (jumlah 2))
    (sudut (id 1) (degree 60.0))
    (sudut (id 2) (degree 120.0))
    (sudut (id 3) (degree 60.0))
    (sudut (id 4) (degree 120.0))
)